version: '3'

services:
  react_material_keyboard:
    build:
      context: ./docker
    volumes:
      - .:/home/app
    user: "node:node"
    ports: 
      - "3000:3000"
    stdin_open: true
    tty: true
